if __name__ == '__main__':
    print('test')
    print('test')
    print('test')
    print('test')
    print('test')
    print('test')
    print('test')
    print('test')
    print('test')
    print('test')
    print('test')